accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout')
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('details/<int:id>/', views.detail, name='detail'),
    path('addgames/', views.add_games, name='add_games'),
    path('editgames/<int:id>/', views.edit_games, name='edit_games'),
    path('deletegames/<int:id>', views.delete_games, name='delete_game'),
    path('addreview/<int:id>', views.add_review, name='add_review'),
    path('editreview/<int:game_id>/<int:review_id>', views.edit_review, name='edit_review'),
    path('deletereview/<int:game_id>/<int:review_id>', views.delete_review, name='delete_review'),
]

movies/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls'))
]

main/models.py
from django.db import models
from django.contrib.auth.models import User


class Game(models.Model):
    name = models.CharField(max_length=300)
    developer = models.CharField(max_length=300)
    platform = models.CharField(max_length=100)
    description = models.TextField(max_length=5000)
    release_date = models.DateField()
    average_rating = models.FloatField(default=0)
    image = models.URLField(default=None, null=True)

    def __str__(self):
        return self.name


class ReviewG(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=1000)
    rating = models.FloatField(default=0)

    def __str__(self):
        return self.user.username

main/forms.py
from django import forms
from .models import *


# class MovieForm(forms.ModelForm):
#     class Meta:
#         model = Movie
#         fields = ('name', 'director', 'cast', 'description', 'release_date', 'image')


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewG
        fields = ('comment', 'rating')


class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ('name', 'developer', 'platform', 'description', 'release_date', 'image')

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *
from django.db.models import Avg


def home(request):
    query = request.GET.get('title')
    all_games = None
    if query:
        all_games = Game.objects.filter(name__icontains=query)
    else:
        all_games = Game.objects.all()

    context = {
        'games': all_games
    }

    return render(request, 'main/index.html', context)


def detail(request, id):
    game = Game.objects.get(id=id)
    reviews = ReviewG.objects.filter(game=id).order_by('-comment')  # idk why '-comment' instead of 'comment'

    average = reviews.aggregate(Avg('rating'))['rating__avg']
    if average is None:
        average = 0
    average = round(average, 2)
    context = {
        'game': game,
        'reviews': reviews,
        'average': average
    }

    return render(request, 'main/details.html', context)


# add games to the database
def add_games(request):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            if request.method == 'POST':
                form = GameForm(request.POST or None)

                if form.is_valid():
                    data = form.save(commit=False)
                    data.save()
                    return redirect('main:home')
            else:
                form = GameForm()
            return render(request, 'main/addgames.html', {'form': form,
                                                           'controller': 'Add Games'})
        # if they are not admin
        else:
            return redirect('main:home')

    # if they are not logged in
    return redirect('accounts:login')


# edit the game
def edit_games(request, id):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            game = Game.objects.get(id=id)

            if request.method == 'POST':
                form = GameForm(request.POST or None, instance=game)

                if form.is_valid():
                    data = form.save(commit=False)
                    data.save()
                    return redirect('main:detail', id)
            else:
                form = GameForm(instance=game)
            return render(request, 'main/addgames.html', {'form': form,
                                                           'controller': 'Edit Games'})
        # if they are not admin
        else:
            return redirect('main:home')

    # if they are not logged in
    return redirect('accounts:login')


# delete games
def delete_games(request, id):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            game = Game.objects.get(id=id)

            game.delete()
            return redirect('main:home')
        # if they are not admin
        else:
            return redirect('main:home')

    # if they are not logged in
    return redirect('accounts:login')


def add_review(request, id):
    if request.user.is_authenticated:
        game = Game.objects.get(id=id)
        if request.method == 'POST':
            form = ReviewForm(request.POST or None)
            if form.is_valid():
                # check if user wrote review for this game
                try:
                    review_wrote_by_user = ReviewG.objects.get(game=game, user=request.user)
                    print(review_wrote_by_user)
                    print(review_wrote_by_user.id)
                    review_wrote_by_user.delete()
                except ReviewG.DoesNotExist:
                    print('ReviewG.DoesNotExist')
                data = form.save(commit=False)
                data.comment = request.POST['comment']
                data.rating = request.POST['rating']
                data.user = request.user
                data.game = game
                data.save()
                return redirect('main:detail', id)
        else:
            form = ReviewForm()
        return render(request, 'main/details.html', {'form': form})
    else:
        return redirect('accounts:login')


# edit the review
def edit_review(request, game_id, review_id):
    if request.user.is_authenticated:
        game = Game.objects.get(id=game_id)

        review = ReviewG.objects.get(game=game, id=review_id)

        if request.user == review.user or request.user.is_superuser:
            if request.method == 'POST':
                form = ReviewForm(request.POST, instance=review)
                if form.is_valid():
                    data = form.save(commit=False)
                    if (data.rating > 10) or (data.rating < 0):
                        error = 'Out of range. Please select rating from 0 to 10.'
                        return render(request, 'main/editreview.html', {'error': error, 'form': form})
                    else:
                        data.save()
                        return redirect('main:detail', game_id)
            else:
                form = ReviewForm(instance=review)
            return render(request, 'main/editreview.html', {'form': form})
        else:
            return redirect('main:detail', game_id)
    else:
        return redirect('accounts:login')


# delete the review
def delete_review(request, game_id, review_id):
    if request.user.is_authenticated:
        game = Game.objects.get(id=game_id)

        review = ReviewG.objects.get(game=game, id=review_id)

        if request.user == review.user or request.user.is_superuser:
            # grant permission to delete
            review.delete()

        return redirect('main:detail', game_id)
    else:
        return redirect('accounts:login')

main/templates/main/addgames.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">{{ controller }}</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                <input type="submit" value="{{ controller }}" class="btn btn-danger">
            </form>
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/addmovies.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">{{ controller }}</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                <input type="submit" value="{{ controller }}" class="btn btn-danger">
            </form>
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <title>Movies</title>

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white">
  <a class="navbar-brand" href="{% url 'main:home' %}">Games</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'main:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main:add_games' %}">Add Games</a>
      </li>

      {% if user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ user.username }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">My Profile</a>

          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
        </div>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
      </li>
      {% endif %}

    </ul>
    <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'main:home' %}">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="title">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

    {% block content %}

    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/main/details.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">
    <br>
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    <img src="{{ game.image }}" alt="{{ game.name }}" class="img-fluid" width="75%">
                </div>
                <div class="col-md-8">
                    <h3 class="text-center">{{ game.name }}</h3>
                    <p>{{ game.description }}</p>
                    <h5>Developer: {{ game.developer }}</h5>
                    <h5>Platform: {{ game.platform }}</h5>
                    <h5>Rating: {{ average }}/10</h5>
                    <h5><i>Release date: {{ game.release_date }}</i></h5>

                    {% if request.user.is_authenticated %}
                        {% if request.user.is_superuser %}
                            <a href="{% url 'main:edit_games' game.id %}" class="btn btn-warning">Edit Game</a>
                            <a href="{% url 'main:delete_game' game.id %}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this?');">Delete Game</a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <br>
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Add Review</h3>
            <form action="{% url 'main:add_review' game.id %}" method="POST">
                {% csrf_token %}
                <label for="comment">Review</label>
                <textarea name="comment" id="comment" cols="30" rows="5" class="form-control"></textarea>

                <label for="rating">Rating</label>
                <input type="range" id="rangeInput"
                    name="rating" min="0" max="10" value="0" step="0.5"
                    oninput="amount.value=rangeInput.value">
                <output name="amount" id="amount" for="rangeInput">0</output>

                <br>
                <input type="submit" class="btn btn-danger" value="Add Review">
            </form>
        </div>
    </div>

    <br>
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Reviews</h3>
            {% for review in reviews %}
                <div class="card-body" style="background-color: #f5eeee;">
                    <div class="row">
                        <div class="col-md-3">
                            <h5 class="text-left">{{ review.user.username }}</h5>
                            <h5>{{ review.rating }}</h5>
                            {% if request.user == review.user or request.user.is_superuser %}
                            <a href="{% url 'main:edit_review' game.id review.id %}">Edit</a>
                            <a href="{% url 'main:delete_review' game.id review.id %}" onclick="return confirm('Are you sure you want to delete this?');">Delete</a>
                            {% endif %}
                        </div>
                        <div class="col-md-9">
                            <p>{{ review.comment }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/editreview.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Edit Review</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                {% if error %}
                    <strong style="color: red;">{{ error }}</strong>
                {% endif %}
                <input type="submit" value="Save Changes" class="btn btn-danger">
            </form>
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}


{% block content %}

<div class="container">
    <br>
    <div class="card" id="backdrop">
        <div class="card-body">
            <div class="row">
                {% for game in games %}
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="text-center">
                                <img src="{{ game.image }}" alt="{{ game.name }}" class="img-fluid" width="75%">
                                <h3 class="text-center">{{ game.name }}</h3>

                                <i> {{ game.release_date }} </i>
                                <a href="{% url 'main:detail' game.id %}">Read More</a>
                            </div>

                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}